-- JD Hospital production schema (Supabase/PostgreSQL)
create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";
create type publication_status as enum ('draft','published','archived');
create type appointment_status as enum ('pending','confirmed','cancelled','completed');
create or replace function set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create table hospitals (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, city text not null, address text, phone text, emergency_phone text, overview text, image_url text, latitude numeric, longitude numeric, facilities jsonb default '[]', status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table specialties (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, overview text, content jsonb default '{}', status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table doctors (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, designation text, qualifications text[], biography text, experience_years int check(experience_years>=0), gender text, languages text[], image_url text, registration_verified boolean default false, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table doctor_hospitals (doctor_id uuid references doctors on delete cascade, hospital_id uuid references hospitals on delete cascade, primary key(doctor_id,hospital_id));
create table doctor_specialties (doctor_id uuid references doctors on delete cascade, specialty_id uuid references specialties on delete cascade, primary key(doctor_id,specialty_id));
create table centres_of_excellence (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, specialty_id uuid references specialties, content jsonb, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table services (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, image_url text, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table support_services (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table health_packages (id uuid primary key default gen_random_uuid(), slug text unique not null, hospital_id uuid references hospitals, name text not null, description text, category text, gender text, min_age int, max_age int, price numeric(10,2) not null check(price>=0), duration_minutes int, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table package_tests (id uuid primary key default gen_random_uuid(), package_id uuid references health_packages on delete cascade, name text not null, created_at timestamptz default now(), updated_at timestamptz default now());
create table doctor_schedules (id uuid primary key default gen_random_uuid(), doctor_id uuid references doctors, hospital_id uuid references hospitals, weekday int check(weekday between 0 and 6), start_time time, end_time time, consultation_type text, slot_minutes int default 30, created_at timestamptz default now(), updated_at timestamptz default now());
create table appointments (id uuid primary key default gen_random_uuid(), appointment_number text unique not null, patient_id uuid references auth.users, patient_name text not null, patient_phone text not null, patient_email text, date_of_birth date, gender text, hospital_id uuid references hospitals, specialty_id uuid references specialties, doctor_id uuid references doctors, appointment_date date, appointment_time time, consultation_type text, reason text, preferred_language text, status appointment_status default 'pending', internal_notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table appointment_status_history (id uuid primary key default gen_random_uuid(), appointment_id uuid references appointments on delete cascade, old_status appointment_status, new_status appointment_status not null, changed_by uuid references auth.users, created_at timestamptz default now(), updated_at timestamptz default now());
create table enquiries (id uuid primary key default gen_random_uuid(), name text not null, phone text, email text, hospital_id uuid references hospitals, subject text, message text not null, enquiry_type text default 'general', status text default 'new', created_at timestamptz default now(), updated_at timestamptz default now());
create table clinics (id uuid primary key default gen_random_uuid(), city text, specialty_id uuid references specialties, doctor_id uuid references doctors, location text, address text, contact text, weekday int, start_time time, end_time time, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table homecare_services (id uuid primary key default gen_random_uuid(), slug text unique, name text, description text, eligibility text, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table patient_stories (id uuid primary key default gen_random_uuid(), slug text unique, title text, content text, hospital_id uuid references hospitals, doctor_id uuid references doctors, media_url text, consent_verified boolean default false, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table videos (id uuid primary key default gen_random_uuid(), slug text unique, title text, category text, youtube_url text, doctor_id uuid references doctors, status publication_status default 'draft', published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table article_categories (id uuid primary key default gen_random_uuid(), slug text unique, name text, created_at timestamptz default now(), updated_at timestamptz default now());
create table articles (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, excerpt text, content text, author text, hero_image text, category_id uuid references article_categories, doctor_id uuid references doctors, status publication_status default 'draft', published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table news_events (id uuid primary key default gen_random_uuid(), slug text unique, title text, category text, content text, image_url text, status publication_status default 'draft', published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table press_releases (id uuid primary key default gen_random_uuid(), slug text unique, title text, content text, status publication_status default 'draft', published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table research_articles (id uuid primary key default gen_random_uuid(), slug text unique, title text, authors text[], department text, journal text, abstract text, pdf_url text, external_url text, status publication_status default 'draft', published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table downloads (id uuid primary key default gen_random_uuid(), title text, category text, file_url text, is_public boolean default true, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table jobs (id uuid primary key default gen_random_uuid(), slug text unique, title text, department text, location text, employment_type text, description text, status publication_status default 'draft', published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table job_applications (id uuid primary key default gen_random_uuid(), job_id uuid references jobs, name text, email text, phone text, resume_path text, cover_letter text, status text default 'new', created_at timestamptz default now(), updated_at timestamptz default now());
create table insurance_providers (id uuid primary key default gen_random_uuid(), name text, logo_url text, tpa_name text, cashless_configured boolean default false, notes text, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table faqs (id uuid primary key default gen_random_uuid(), question text, answer text, category text, sort_order int default 0, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table testimonials (id uuid primary key default gen_random_uuid(), name text, quote text, consent_verified boolean default false, status publication_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table admins (user_id uuid primary key references auth.users on delete cascade, role text default 'editor', created_at timestamptz default now(), updated_at timestamptz default now());
create table site_settings (id uuid primary key default gen_random_uuid(), key text unique, value jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table navigation_items (id uuid primary key default gen_random_uuid(), label text, href text, parent_id uuid references navigation_items, sort_order int default 0, published boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());

create index doctors_slug_idx on doctors(slug); create index hospitals_slug_idx on hospitals(slug); create index specialties_slug_idx on specialties(slug); create index appointments_status_idx on appointments(status); create index appointments_doctor_idx on appointments(doctor_id); create index appointments_hospital_idx on appointments(hospital_id); create index articles_published_idx on articles(published_at); create index doctors_search_idx on doctors using gin ((name || ' ' || coalesce(designation,'')) gin_trgm_ops);

create or replace function is_admin() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from admins where user_id=auth.uid()) $$;
-- Enable RLS on every application table.
do $$ declare t text; begin foreach t in array array['hospitals','specialties','doctors','doctor_hospitals','doctor_specialties','centres_of_excellence','services','support_services','health_packages','package_tests','doctor_schedules','appointments','appointment_status_history','enquiries','clinics','homecare_services','patient_stories','videos','article_categories','articles','news_events','press_releases','research_articles','downloads','jobs','job_applications','insurance_providers','faqs','testimonials','admins','site_settings','navigation_items'] loop execute format('alter table %I enable row level security',t); end loop; end $$;
-- Published public data only.
do $$ declare t text; begin foreach t in array array['hospitals','specialties','doctors','centres_of_excellence','services','support_services','health_packages','clinics','homecare_services','patient_stories','videos','articles','news_events','press_releases','research_articles','jobs','insurance_providers','faqs','testimonials'] loop execute format('create policy "public read published" on %I for select using (status = ''published'')',t); end loop; end $$;
create policy "public downloads" on downloads for select using (status='published' and is_public=true);
create policy "admin all hospitals" on hospitals for all using(is_admin()) with check(is_admin());
-- Repeat admin policy across managed tables via SQL loop.
do $$ declare t text; begin foreach t in array array['specialties','doctors','doctor_hospitals','doctor_specialties','centres_of_excellence','services','support_services','health_packages','package_tests','doctor_schedules','appointments','appointment_status_history','enquiries','clinics','homecare_services','patient_stories','videos','article_categories','articles','news_events','press_releases','research_articles','downloads','jobs','job_applications','insurance_providers','faqs','testimonials','site_settings','navigation_items'] loop execute format('create policy "admin full access" on %I for all using (is_admin()) with check (is_admin())',t); end loop; end $$;
create policy "patient reads own appointments" on appointments for select using(patient_id=auth.uid());
-- Private submissions happen through validated server routes using the service role, never public client inserts.

insert into storage.buckets(id,name,public) values ('hospital-images','hospital-images',true),('doctor-images','doctor-images',true),('service-images','service-images',true),('package-images','package-images',true),('article-images','article-images',true),('career-resumes','career-resumes',false),('documents','documents',true) on conflict do nothing;
