import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,Search,CalendarDays,Building2,Siren,HeartPulse,Brain,Bone,Ribbon,Activity,Droplets,Wind,Stethoscope,ShieldCheck,CheckCircle2,PlayCircle,BookOpen,HousePlus,MapPin} from 'lucide-react';
import {getDoctors,getSpecialties,getHospitals,getPackages,getArticles,getServices,getVideos,getPatientStories,getSiteMetrics} from '@/lib/repositories';
const icons:any={HeartPulse,Brain,Bone,Ribbon,Activity,Droplets,Wind,Stethoscope};
const Updating=({label}:{label:string})=><div className="empty compact"><h3>{label} is being updated.</h3><p>Please contact our care team for current information.</p><Link className="btn btn-secondary" href="/contact">Contact us</Link></div>;
export default async function Home(){const [doctors,specialties,hospitals,packages,articles,services,videos,stories,metrics]=await Promise.all([getDoctors(),getSpecialties(),getHospitals(),getPackages(),getArticles(),getServices(),getVideos(),getPatientStories(),getSiteMetrics()]);return <>
<section className="hero hero-v2"><div className="container hero-grid"><div className="hero-content"><span className="eyebrow">Advanced care <b>•</b> Human compassion</span><h1>Expert Care. Advanced Medicine. <span>A Healthier Tomorrow.</span></h1><p>Connect with experienced specialists, trusted hospitals and comprehensive care designed around your health journey.</p><div className="hero-buttons"><Link className="btn btn-primary" href="/doctors">Find a doctor <ArrowRight/></Link><Link className="btn btn-secondary" href="/book-appointment">Book an appointment</Link></div><Link className="emergency-text" href="/emergency"><Siren/> 24/7 emergency care <ArrowRight/></Link></div><div className="hero-visual"><Image src="/images/hero-consultation.jpg" priority sizes="(max-width: 760px) 100vw, 52vw" width={1800} height={1200} alt="Doctor consulting with a patient in a modern hospital room"/><div className="hero-caption"><ShieldCheck/><span><strong>Specialist care</strong><small>Across multiple disciplines</small></span></div></div></div>
<form className="search-panel search-panel-v2" action="/search"><div className="search-heading"><span className="eyebrow">How can we help you today?</span><div className="search-tabs" role="group" aria-label="Search type"><label><input type="radio" name="type" value="doctor" defaultChecked/> Find a doctor</label><label><input type="radio" name="type" value="hospital"/> Find a hospital</label><label><input type="radio" name="type" value="specialty"/> Explore specialties</label></div></div><div className="field search-main"><label htmlFor="hero-q">Search care</label><input id="hero-q" name="q" placeholder="Search doctor, specialty or hospital"/></div><div className="field"><label>City</label><select name="location"><option value="">All locations</option>{[...new Set(hospitals.map(h=>h.city))].map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Specialty</label><select name="specialty"><option value="">All specialties</option>{specialties.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select></div><button className="btn btn-primary" style={{alignSelf:'end'}}><Search/> Search</button><div className="trust-points">{[[ShieldCheck,'Trusted care'],[Activity,'Advanced technology'],[Stethoscope,'Experienced specialists'],[HeartPulse,'Patient-first approach']].map(([I,t]:any)=><span key={t}><I/>{t}</span>)}</div></form></section>

<section className="section quick-section"><div className="container"><div className="section-head"><div><span className="eyebrow">Care, without the complexity</span><h2>How can we help today?</h2></div><p>Clear pathways to the care you need, whether you are planning ahead or need help now.</p></div><div className="quick-grid">{[[Search,'Find a doctor','Search by specialty, hospital and language.','/doctors'],[CalendarDays,'Book appointment','Choose a clinician and an available time.','/book-appointment'],[Building2,'Find a hospital','Explore hospitals, facilities and directions.','/hospitals'],[Siren,'Emergency care','Get urgent numbers and directions now.','/emergency']].map(([I,t,d,l]:any)=><Link href={l} className="quick-card" key={t}><span className="icon-box"><I/></span><h3>{t}</h3><p>{d}</p><span className="quick-link">Explore <ArrowRight/></span></Link>)}</div></div></section>

<section className="trust"><div className="container trust-grid"><div><span className="eyebrow">Built around trust</span><h2>Care measured by what matters.</h2>{metrics.demo&&<small className="metric-disclosure">Demonstration network data</small>}</div>{metrics.items.length?metrics.items.slice(0,4).map(x=><div className="stat" key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>):<div className="trust-copy">Verified network information is currently being updated.</div>}</div></section>

<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Find a specialist</span><h2>The right expertise, easier to find.</h2></div><Link href="/doctors" className="btn btn-secondary">Search all doctors</Link></div>{doctors.length?<div className="specialist-list">{doctors.slice(0,4).map(d=><Link href={`/doctors/${d.slug}`} key={d.id}><span className="specialist-avatar">{d.initials}</span><span><strong>{d.name}</strong><small>{d.specialty} · {d.hospital}</small></span><ArrowRight/></Link>)}</div>:<Updating label="Specialist information"/>}</div></section>

<section className="section section-tint"><div className="container"><div className="section-head"><div><span className="eyebrow">Centres of excellence</span><h2>Specialists who work together.</h2></div><Link className="btn btn-secondary" href="/specialties">View all specialties</Link></div>{specialties.length?<div className="specialty-grid">{specialties.slice(0,8).map(s=>{const I=icons[s.icon]||Stethoscope;return <Link className="specialty-card" href={`/specialties/${s.slug}`} key={s.id}><span className="icon-box"><I/></span><h3>{s.name}</h3><p>{s.desc}</p><span className="quick-link">Explore specialty <ArrowRight/></span></Link>})}</div>:<Updating label="Specialty information"/>}</div></section>

<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Hospital network</span><h2>Advanced care, closer to home.</h2></div><Link className="btn btn-secondary" href="/hospitals">Explore all hospitals</Link></div>{hospitals.length?<div className="hospital-showcase">{hospitals.slice(0,3).map(h=><article className="hospital-feature-card" key={h.id}><Image src={h.image_url||'/images/hospital-building.jpg'} sizes="(max-width: 760px) 100vw, 33vw" width={1600} height={1067} alt={h.image_url?`${h.name} hospital building`:'Illustrative modern healthcare building facade'}/><div><span className="eyebrow"><MapPin/> {h.city}</span><h3>{h.name}</h3><p>{h.overview||h.address}</p><small><Siren/> Emergency information available</small><div className="card-actions"><Link className="btn btn-secondary" href={`/hospitals/${h.slug}`}>View hospital</Link><a className="btn btn-ghost" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/directions?to=${h.latitude},${h.longitude}`}>Directions</a></div></div></article>)}</div>:<Updating label="Hospital information"/>}</div></section>

<section className="section why-section"><div className="container"><div className="care-feature"><Image src="/images/clinical-team.jpg" sizes="(max-width: 760px) 100vw, 50vw" width={1600} height={1067} alt="Clinical team reviewing diagnostic imaging together"/><div className="care-copy"><span className="eyebrow">Why choose JD Hospital</span><h2>One team. One clear care plan.</h2><p>Multidisciplinary teams connect assessment, diagnostics, treatment planning and recovery support around each patient.</p><div className="care-list">{['Coordinated case review','Advanced diagnostics','Dedicated care navigation','Recovery and rehabilitation'].map(x=><div key={x}><CheckCircle2/>{x}</div>)}</div><Link href="/about" className="btn btn-secondary">Our care philosophy</Link></div></div></div></section>

<section className="section section-tint"><div className="container"><div className="section-head"><div><span className="eyebrow">Clinical services</span><h2>Support across every stage of care.</h2></div><Link className="btn btn-secondary" href="/services">Explore services</Link></div>{services.length?<div className="service-grid">{services.slice(0,6).map((s,i)=><Link href="/services" className="service-card" key={s.id}><span>0{i+1}</span><h3>{s.name}</h3><p>{s.description}</p><ArrowRight/></Link>)}</div>:<Updating label="Service information"/>}</div></section>

<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Preventive health</span><h2>Health checks with a clear purpose.</h2></div><Link className="btn btn-secondary" href="/health-packages">Compare packages</Link></div>{packages.length?<div className="doctor-grid">{packages.slice(0,3).map(p=><article className="quick-card package-card" key={p.id}><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><p>{p.hospital} · {p.tests} tests · {p.duration}</p><strong className="package-price">₹{p.price.toLocaleString('en-IN')}</strong><Link className="quick-link" href={`/health-packages/${p.slug}`}>View package <ArrowRight/></Link></article>)}</div>:<Updating label="Package information"/>}</div></section>

<section className="section section-tint"><div className="container"><div className="section-head"><div><span className="eyebrow">Doctor spotlight</span><h2>Meet our specialists.</h2></div><Link href="/doctors" className="btn btn-secondary">View all doctors</Link></div>{doctors.length?<div className="doctor-carousel">{doctors.slice(0,6).map(d=><article className="doctor-card" key={d.id}><div className="doctor-photo"><span className="demo-badge">DEMO PROFILE</span>{d.image_url?<Image src={d.image_url} fill sizes="300px" alt={`${d.name}, ${d.specialty}`}/>:<div className="portrait">{d.initials}</div>}</div><div className="doctor-body"><span className="eyebrow">{d.specialty}</span><h3>{d.name}</h3><p>{d.designation}</p><div className="meta"><span>{d.experience} years</span><span>{d.hospital}</span></div><div className="card-actions"><Link href={`/doctors/${d.slug}`} className="btn btn-secondary">Profile</Link><Link href={`/book-appointment?doctor=${d.id}`} className="btn btn-primary">Book</Link></div></div></article>)}</div>:<Updating label="Doctor profiles"/>}</div></section>

<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Patient stories</span><h2>Every journey deserves to be heard.</h2></div><Link href="/patient-stories" className="btn btn-secondary">View stories</Link></div>{stories.length?<div className="story-grid">{stories.slice(0,2).map(s=><article key={s.id}><span className="story-quote">“</span><h3>{s.title}</h3><p>{s.content}</p><small>Fictional demonstration story · No outcome claimed</small></article>)}</div>:<Updating label="Patient stories"/>}</div></section>

<section className="section section-tint"><div className="container"><div className="section-head"><div><span className="eyebrow">Health insights</span><h2>Clear information for better conversations.</h2></div><Link href="/health-library" className="btn btn-secondary">Health library</Link></div>{articles.length?<div className="article-grid">{articles.slice(0,3).map(a=><article className="article-card" key={a.id}><BookOpen/><span className="eyebrow">{a.category}</span><h3><Link href={`/health-library/${a.slug}`}>{a.title}</Link></h3><p>{a.excerpt}</p><Link className="quick-link" href={`/health-library/${a.slug}`}>Read article <ArrowRight/></Link></article>)}</div>:<Updating label="Health articles"/>}</div></section>

<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Medical videos</span><h2>Health topics, explained simply.</h2></div><Link href="/videos" className="btn btn-secondary">Video centre</Link></div>{videos.length?<div className="video-grid">{videos.slice(0,3).map(v=><Link className="video-card" href="/videos" key={v.id}><div><PlayCircle/><span>Watch</span></div><small>{v.category}</small><h3>{v.title}</h3></Link>)}</div>:<Updating label="Medical videos"/>}</div></section>

<section className="section homecare-band"><div className="container"><div><span className="icon-box"><HousePlus/></span><span className="eyebrow">Home healthcare</span><h2>Hospital expertise, thoughtfully delivered at home.</h2><p>Request doctor visits, nursing, physiotherapy, sample collection and equipment support through one coordinated service.</p><Link className="btn btn-primary" href="/home-healthcare#request">Request home care</Link></div><Image src="/images/hero-consultation.jpg" width={1800} height={1200} sizes="(max-width: 760px) 100vw, 45vw" alt="Healthcare professional discussing care with a patient"/></div></section>

<section className="emergency-band"><div className="container"><div><span className="eyebrow">Emergency now</span><h2>Urgent care cannot wait.</h2><p>Call emergency services or find the nearest JD Hospital emergency department.</p></div><div className="hero-buttons"><a className="btn emergency-white" href="tel:112"><Siren/> Call 112</a><Link className="btn emergency-outline" href="/emergency">Emergency locations</Link></div></div></section>

<section className="section final-cta"><div className="container"><span className="eyebrow">Your next step</span><h2>Find the care that is right for you.</h2><p>Search specialists or request an appointment with our care team.</p><div className="hero-buttons"><Link className="btn btn-primary" href="/doctors">Find a doctor</Link><Link className="btn btn-secondary" href="/book-appointment">Book appointment</Link></div><p className="demo-disclosure"><strong>Demonstration platform:</strong> JD Hospital, its locations and clinician profiles are fictional. No credentials, accreditations or clinical outcomes are claimed.</p></div></section>
</>}
