import { publicClient } from './supabase';
import { doctors as demoDoctors, hospitals as demoHospitals, specialties as demoSpecialties, packages as demoPackages } from './data';

export type Doctor={id:string;slug:string;name:string;designation:string;qualification:string;specialty:string;specialty_id?:string;hospital:string;hospital_id?:string;city?:string;experience:number;languages:string[];gender:string;initials:string;image_url?:string|null};
export type Hospital={id:string;slug:string;name:string;city:string;address:string;phone:string;emergency:string;specialties:string[];beds?:string;image_url?:string|null;latitude?:number|null;longitude?:number|null;overview?:string|null};
export type Specialty={id:string;slug:string;name:string;icon:string;desc:string};
export type HealthPackage={id:string;slug:string;name:string;hospital:string;hospital_id?:string;category:string;price:number;tests:number;duration:string;description?:string;test_names?:string[];eligibility?:string;preparation?:string};
const demoPortraits=['/images/doctor-01.jpg','/images/doctor-02.jpg','/images/doctor-03.jpg','/images/doctor-04.jpg','/images/doctor-05.jpg','/images/doctor-06.jpg'];
const dd:Doctor[]=demoDoctors.map((d,i)=>({...d,id:`demo-doctor-${i+1}`,qualification:d.qualification,image_url:demoPortraits[i%demoPortraits.length]}));
const dh:Hospital[]=demoHospitals.map((h,i)=>({...h,id:`demo-hospital-${i+1}`,latitude:[21.1458,18.5204,19.076][i],longitude:[79.0882,73.8567,72.8777][i]}));
const ds:Specialty[]=demoSpecialties.map((s,i)=>({...s,id:`demo-specialty-${i+1}`}));
const dp:HealthPackage[]=demoPackages.map((p,i)=>({...p,id:`demo-package-${i+1}`,hospital_id:dh.find(h=>h.name===p.hospital)?.id||dh[0]?.id,test_names:['Complete blood count','Blood glucose profile','Lipid profile','Liver function markers','Kidney function markers','Physician consultation'],eligibility:'Adults seeking a clinician-guided preventive health review. Final eligibility is confirmed by the hospital.',preparation:'Fasting may be required for selected tests. The hospital will provide instructions after confirming the request.'}));

export async function getHospitals():Promise<Hospital[]>{const c=publicClient();if(!c)return dh;const {data,error}=await c.from('hospitals').select('id,slug,name,city,address,phone,emergency_phone,overview,image_url,latitude,longitude,facilities').eq('status','published').order('name');if(error){console.error('[data] hospitals query failed',error.message);return []}return (data||[]).map((h:any)=>({id:h.id,slug:h.slug,name:h.name,city:h.city,address:h.address||'',phone:h.phone||'',emergency:h.emergency_phone||'',specialties:[],image_url:h.image_url,latitude:h.latitude?Number(h.latitude):null,longitude:h.longitude?Number(h.longitude):null,overview:h.overview}));}
export async function getHospital(slug:string){const hospitals=await getHospitals();const hospital=hospitals.find(x=>x.slug===slug);if(!hospital)return null;const doctors=await getDoctors();return {...hospital,specialties:[...new Set(doctors.filter(d=>d.hospital_id===hospital.id||d.hospital===hospital.name).map(d=>d.specialty))]}}
export async function getSpecialties():Promise<Specialty[]>{const c=publicClient();if(!c)return ds;const {data,error}=await c.from('specialties').select('id,slug,name,overview').eq('status','published').order('name');if(error){console.error('[data] specialties query failed',error.message);return []}return (data||[]).map((s:any)=>({id:s.id,slug:s.slug,name:s.name,icon:'Stethoscope',desc:s.overview||''}));}
export async function getSpecialty(slug:string){return (await getSpecialties()).find(x=>x.slug===slug)||null}
export async function getDoctors():Promise<Doctor[]>{const c=publicClient();if(!c)return dd;const {data,error}=await c.from('doctors').select('id,slug,name,designation,qualifications,experience_years,gender,languages,image_url,doctor_specialties(specialties(id,name)),doctor_hospitals(hospitals(id,name,city))').eq('status','published').order('name').limit(100);if(error){console.error('[data] doctors query failed',error.message);return []}return (data||[]).map((d:any)=>{const sp=d.doctor_specialties?.[0]?.specialties;const hp=d.doctor_hospitals?.[0]?.hospitals;return {id:d.id,slug:d.slug,name:d.name,designation:d.designation||'Consultant',qualification:d.qualifications?.join(', ')||'Credentials pending verification',specialty:sp?.name||'Multispeciality Care',specialty_id:sp?.id,hospital:hp?.name||'JD Hospital',hospital_id:hp?.id,city:hp?.city,experience:d.experience_years||0,languages:d.languages||[],gender:d.gender||'',initials:d.name.split(' ').filter(Boolean).slice(-2).map((x:string)=>x[0]).join('').toUpperCase(),image_url:d.image_url}})}
export async function getDoctor(slug:string){return (await getDoctors()).find(x=>x.slug===slug)||null}
export async function getPackages():Promise<HealthPackage[]>{const c=publicClient();if(!c)return dp;const {data,error}=await c.from('health_packages').select('id,slug,name,description,category,price,duration_minutes,hospital_id,eligibility,preparation,hospitals(name),package_tests(id,name)').eq('status','published').order('name');if(error){console.error('[data] packages query failed',error.message);return []}return (data||[]).map((p:any)=>({id:p.id,slug:p.slug,name:p.name,hospital:p.hospitals?.name||'JD Hospital',hospital_id:p.hospital_id,category:p.category||'Preventive',price:Number(p.price),tests:p.package_tests?.length||0,duration:`${Math.max(1,Math.round((p.duration_minutes||180)/60))} hours`,description:p.description,test_names:(p.package_tests||[]).map((t:any)=>t.name),eligibility:p.eligibility,preparation:p.preparation}));}
export async function getPackage(slug:string){return (await getPackages()).find(x=>x.slug===slug)||null}
export type Article={id:string;slug:string;title:string;excerpt:string;content:string;author:string;published_at:string;category:string;hero_image?:string|null;doctor?:{name:string;slug:string}|null};
const demoArticles:Article[]=[{id:'demo-article-1',slug:'understanding-preventive-health-checks',title:'Understanding preventive health checks',excerpt:'How to prepare for a useful conversation about screening and prevention.',content:'Preventive care begins with a conversation about your age, health history, family history and individual risk. Screening is most useful when it is selected for a clear reason. Before a health check, collect your current medicine list and previous reports. Ask which tests are appropriate for you, how to prepare, and when results will be discussed. A screening result alone is not a diagnosis. Your clinician interprets it alongside your symptoms, examination and history.',author:'JD Health Editorial Team',published_at:'2026-09-12',category:'Preventive Care'},{id:'demo-article-2',slug:'preparing-for-a-specialist-visit',title:'Preparing for a specialist visit',excerpt:'A simple checklist to make your consultation clearer and more productive.',content:'Write down your main concern, when it began and what makes it better or worse. Bring recent reports, imaging, prescriptions and a complete medicine list. Include vitamins and supplements. Prepare two or three questions that matter most to you. If language or accessibility support would help, request it before the visit. Seek emergency care rather than waiting for an appointment if symptoms are severe or rapidly worsening.',author:'JD Health Editorial Team',published_at:'2026-09-08',category:'Patient Guides'},{id:'demo-article-3',slug:'supporting-recovery-at-home',title:'Supporting recovery at home',excerpt:'Practical ways families can support a safe transition after hospital care.',content:'Before discharge, make sure you understand medicines, wound care, food and activity advice, follow-up dates and warning signs. Keep written instructions accessible. Arrange transport, mobility support and help with meals where needed. Contact the clinical team if instructions are unclear. For severe breathlessness, chest pain, confusion, heavy bleeding or another urgent concern, use emergency services immediately.',author:'JD Health Editorial Team',published_at:'2026-09-02',category:'Recovery'}];
export async function getArticles():Promise<Article[]>{const c=publicClient();if(!c)return demoArticles;const {data,error}=await c.from('articles').select('id,slug,title,excerpt,content,author,hero_image,published_at,article_categories(name),doctors(name,slug)').eq('status','published').order('published_at',{ascending:false}).limit(60);if(error){console.error('[data] articles query failed',error.message);return []}return (data||[]).map((a:any)=>({id:a.id,slug:a.slug,title:a.title,excerpt:a.excerpt||'',content:a.content||'',author:a.author||'JD Health Editorial Team',hero_image:a.hero_image,published_at:a.published_at,category:a.article_categories?.name||'Health information',doctor:a.doctors||null}))}
export async function getArticle(slug:string){return (await getArticles()).find(x=>x.slug===slug)||null}
export type Service={id:string;slug:string;name:string;description:string;image_url?:string|null};
export type Video={id:string;slug:string;title:string;category:string;youtube_url:string};
export type PatientStory={id:string;slug:string;title:string;content:string;media_url?:string|null};
const demoServices:Service[]=[{id:'service-1',slug:'emergency-care',name:'Emergency & trauma care',description:'Rapid assessment, stabilisation and specialist escalation around the clock.'},{id:'service-2',slug:'diagnostics',name:'Advanced diagnostics',description:'Connected laboratory, radiology and imaging services supporting clinical decisions.'},{id:'service-3',slug:'rehabilitation',name:'Rehabilitation',description:'Physiotherapy, nutrition and recovery planning shaped around individual goals.'}];
const demoVideos:Video[]=[{id:'video-1',slug:'preparing-for-a-heart-consultation',title:'Preparing for a heart consultation',category:'Cardiac Sciences',youtube_url:''},{id:'video-2',slug:'understanding-joint-pain',title:'When joint pain needs attention',category:'Orthopaedics',youtube_url:''},{id:'video-3',slug:'preventive-health-conversations',title:'Making preventive care conversations useful',category:'Preventive Care',youtube_url:''}];
const demoStories:PatientStory[]=[{id:'story-1',slug:'a-clearer-path-to-mobility',title:'A clearer path back to mobility',content:'A fictional demonstration story about coordinated assessment, rehabilitation planning and family support.'},{id:'story-2',slug:'supported-through-complex-care',title:'Supported through complex care',content:'A fictional demonstration story showing how a care navigator can make a complex hospital journey easier to understand.'}];
export async function getServices():Promise<Service[]>{const c=publicClient();if(!c)return demoServices;const {data,error}=await c.from('services').select('id,slug,name,description,image_url').eq('status','published').order('name');if(error){console.error('[data] services query failed',error.message);return []}return (data||[]) as Service[]}
export async function getVideos():Promise<Video[]>{const c=publicClient();if(!c)return demoVideos;const {data,error}=await c.from('videos').select('id,slug,title,category,youtube_url').eq('status','published').order('published_at',{ascending:false}).limit(12);if(error){console.error('[data] videos query failed',error.message);return []}return (data||[]) as Video[]}
export async function getPatientStories():Promise<PatientStory[]>{const c=publicClient();if(!c)return demoStories;const {data,error}=await c.from('patient_stories').select('id,slug,title,content,media_url').eq('status','published').eq('consent_verified',true).order('created_at',{ascending:false}).limit(6);if(error){console.error('[data] patient stories query failed',error.message);return []}return (data||[]) as PatientStory[]}
export async function getSiteMetrics(){const c=publicClient();if(!c)return {demo:true,items:[{label:'Hospitals',value:String(dh.length)},{label:'Specialties',value:String(ds.length)},{label:'Clinician profiles',value:String(dd.length)},{label:'Emergency care',value:'24/7'}]};const keys=['hospitals_count','specialties_count','doctors_count','years_of_service','patients_served'];const {data,error}=await c.from('site_settings').select('key,value').in('key',keys);if(error){console.error('[data] metrics query failed',error.message);return {demo:false,items:[]}}const labels:Record<string,string>={hospitals_count:'Hospitals',specialties_count:'Specialties',doctors_count:'Doctors',years_of_service:'Years of service',patients_served:'Patients served'};return {demo:false,items:(data||[]).filter((x:any)=>x.value?.verified===true).map((x:any)=>({label:labels[x.key]||x.key,value:String(x.value.value)}))}}
export type Job={id:string;slug:string;title:string;department:string;location:string;employment_type:string;description:string};
const demoJobs:Job[]=[{id:'demo-job-1',slug:'staff-nurse-critical-care',title:'Staff Nurse — Critical Care',department:'Nursing',location:'Nagpur',employment_type:'Full-time',description:'Join a multidisciplinary critical care team focused on safe, compassionate and evidence-led nursing practice.'},{id:'demo-job-2',slug:'patient-experience-executive',title:'Patient Experience Executive',department:'Patient Services',location:'Pune',employment_type:'Full-time',description:'Help patients and families navigate appointments, admissions and follow-up with clarity and empathy.'}];
export async function getJobs():Promise<Job[]>{const c=publicClient();if(!c)return demoJobs;const {data,error}=await c.from('jobs').select('id,slug,title,department,location,employment_type,description').eq('status','published').order('published_at',{ascending:false});if(error){console.error('[data] jobs query failed',error.message);return []}return (data||[]) as Job[]}
export async function getJob(slug:string){return (await getJobs()).find(x=>x.slug===slug)||null}
export async function globalSearch(q:string,filters:{location?:string;specialty?:string;type?:string}={}){const term=q.trim().toLowerCase();const client=publicClient();if(client&&term&&!filters.location&&!filters.specialty){const {data,error}=await client.rpc('global_search',{p_query:q,p_limit:60});if(!error){const rows=(data||[]) as any[];const pick=(kind:string)=>rows.filter(r=>r.entity_type===kind).map(r=>({id:r.id,slug:r.slug,name:r.title,title:r.title,category:r.subtitle,desc:r.subtitle,description:r.subtitle}));const grouped={doctors:pick('doctor'),hospitals:pick('hospital'),specialties:pick('specialty'),packages:pick('package'),articles:pick('article'),services:pick('service'),videos:pick('video')};if(filters.type==='doctor')return {...grouped,hospitals:[],specialties:[],packages:[],articles:[],services:[],videos:[]};if(filters.type==='hospital')return {...grouped,doctors:[],specialties:[],packages:[],articles:[],services:[],videos:[]};if(filters.type==='specialty')return {...grouped,doctors:[],hospitals:[],packages:[],articles:[],services:[],videos:[]};return grouped}console.error('[data] full-text search failed',error.message)}const [doctors,hospitals,specialties,packages,articles,services,videos]=await Promise.all([getDoctors(),getHospitals(),getSpecialties(),getPackages(),getArticles(),getServices(),getVideos()]);const hit=(...v:(string|undefined)[])=>!term||v.join(' ').toLowerCase().includes(term);const specialtyName=specialties.find(s=>s.slug===filters.specialty)?.name;const all={doctors:doctors.filter(x=>hit(x.name,x.specialty,x.hospital)&&(!filters.location||x.city===filters.location||x.hospital.includes(filters.location))&&(!specialtyName||x.specialty===specialtyName)),hospitals:hospitals.filter(x=>hit(x.name,x.city,x.address)&&(!filters.location||x.city===filters.location)),specialties:specialties.filter(x=>hit(x.name,x.desc)&&(!filters.specialty||x.slug===filters.specialty)),packages:packages.filter(x=>hit(x.name,x.category,x.hospital)&&(!filters.location||x.hospital.includes(filters.location))),articles:articles.filter(x=>hit(x.title,x.excerpt,x.category)),services:services.filter(x=>hit(x.name,x.description)),videos:videos.filter(x=>hit(x.title,x.category))};if(filters.type==='doctor')return {...all,hospitals:[],specialties:[],packages:[],articles:[],services:[],videos:[]};if(filters.type==='hospital')return {...all,doctors:[],specialties:[],packages:[],articles:[],services:[],videos:[]};if(filters.type==='specialty')return {...all,doctors:[],hospitals:[],packages:[],articles:[],services:[],videos:[]};return all}
