import {notFound} from 'next/navigation';import Link from 'next/link';import {HeartHandshake} from 'lucide-react';import EnquiryForm from '@/components/EnquiryForm';import HomecareForm from '@/components/HomecareForm';
const pages:Record<string,{title:string;eyebrow:string;intro:string;sections:[string,string][];cta?:string}>={
'centres-of-excellence':{title:'Centres of excellence',eyebrow:'Complex care, connected',intro:'Multidisciplinary expertise, advanced technology and thoughtful support—brought together around each patient.',sections:[['Connected clinical teams','Specialists review complex cases together, creating one clear and coordinated plan.'],['Advanced care environments','Purpose-built facilities support diagnosis, procedures, recovery and rehabilitation.'],['Support beyond treatment','Care navigators help patients and families understand the next step.']]},
'services':{title:'Clinical services',eyebrow:'Care across every stage',intro:'Explore coordinated clinical, diagnostic and support services across the JD Hospital network.',sections:[['Diagnostics','Laboratory medicine, imaging and specialist testing in one connected pathway.'],['Day care & procedures','Efficient, clinically supervised care designed around safety and comfort.'],['Rehabilitation','Physiotherapy, nutrition and recovery support tailored to individual goals.']]},
'support-services':{title:'Support services',eyebrow:'Behind every moment of care',intro:'The essential clinical and operational services that keep patient care safe, responsive and connected.',sections:[['24/7 emergency','Rapid assessment, stabilisation and specialist escalation.'],['Pharmacy & pathology','Integrated services designed for accuracy and continuity.'],['Critical care','Specialist teams and advanced monitoring for patients needing intensive support.']]},
'home-healthcare':{title:'Hospital expertise, at home',eyebrow:'JD Home Healthcare',intro:'Clinically coordinated home visits and recovery support, requested through one care team.',sections:[['Doctor & nursing visits','Planned visits subject to clinical assessment and service availability.'],['Physiotherapy','Goal-based recovery and mobility support in familiar surroundings.'],['Diagnostics & equipment','Home sample collection and equipment coordination where available.']]},
'clinics':{title:'Specialty clinics',eyebrow:'Planned specialist access',intro:'Find demonstration outreach clinics by location, specialty and day.',sections:[['Nagpur Heart Clinic','Central Avenue · Monday & Thursday · 10:00–14:00'],['Pune Joint Clinic','Baner Road · Tuesday · 09:30–13:00'],['Mumbai Wellness Clinic','Andheri East · Saturday · 08:00–12:00']]},
'patient-stories':{title:'Stories of courage and care',eyebrow:'Patient stories',intro:'Fictional demonstration stories that show how patient experiences may be presented with consent.',sections:[['A clearer path back to mobility','Demo story · Orthopaedics · No real patient depicted.'],['Confidence after cardiac rehabilitation','Demo story · Cardiac Sciences · No clinical outcome claimed.'],['Supported at every step','Demo story · Oncology · No real patient depicted.']]},
'videos':{title:'Health, explained clearly',eyebrow:'Doctor videos',intro:'Short educational videos from specialists. Demo entries do not contain medical advice.',sections:[['Understanding blood pressure','General health · 05:20'],['Everyday habits for heart health','Cardiac Sciences · 06:40'],['When joint pain needs attention','Orthopaedics · 04:55']]},
'health-library':{title:'Health library',eyebrow:'Knowledge for better conversations',intro:'Evidence-informed educational resources to help you prepare for care and ask useful questions.',sections:[['A practical guide to preventive screening','Preventive care · 6 min read'],['Understanding common heart tests','Heart health · 8 min read'],['Supporting recovery after a hospital stay','General health · 5 min read']]},
'news-events':{title:'News & events',eyebrow:'From across JD Hospital',intro:'Updates, community programmes and events from our demonstration hospital network.',sections:[['Community wellness weekend announced','News · 18 September 2026'],['Clinical education series for families','Event · 10 September 2026'],['New patient navigation programme','Update · 02 September 2026']]},
'press-releases':{title:'Press releases',eyebrow:'Media centre',intro:'Search official announcements and institutional updates.',sections:[['JD Hospital introduces coordinated patient navigation','Demo release · 2026'],['New preventive health initiative announced','Demo release · 2026']]},
'research':{title:'Research & innovation',eyebrow:'Better questions. Better care.',intro:'A demonstration directory for publications, clinical research and academic collaboration.',sections:[['Clinical outcomes research','Publication metadata, abstracts and external journal links.'],['Translational innovation','Responsible evaluation of technology in clinical environments.'],['Academic collaboration','Programmes designed with ethics, governance and patient safety.']]},
'downloads':{title:'Downloads',eyebrow:'Documents & forms',intro:'Access public forms, policies, reports and patient information documents.',sections:[['Patient registration form','PDF · Demo document'],['Accessibility statement','PDF · Demo document'],['Annual quality report','PDF · Demo document']]},
'careers':{title:'Build care that matters',eyebrow:'Careers at JD Hospital',intro:'Join multidisciplinary teams committed to clinical quality, empathy and continuous learning.',sections:[['Clinical roles','Doctors, nurses, allied health and pharmacy.'],['Operations & technology','Patient experience, administration, data and engineering.'],['Learning culture','Structured onboarding, education and leadership development.']]},
'insurance':{title:'Insurance & cashless guidance',eyebrow:'Plan your visit',intro:'Understand documentation and the authorisation process before your visit.',sections:[['Eligibility must be confirmed','Network listing does not guarantee cashless approval. Contact your insurer and hospital desk.'],['Documents to carry','Photo ID, policy card, referral and relevant medical records.'],['Authorisation process','Our desk can submit documentation; approval remains with the insurer or TPA.']]},
'international-patients':{title:'Care across borders',eyebrow:'International patient services',intro:'A dedicated coordination pathway for treatment enquiries, travel planning and hospital visits.',sections:[['Before you travel','Share records securely for clinical review and an indicative care plan.'],['During your stay','Coordination support for appointments, interpretation and local information.'],['After you return','Records and follow-up planning for continuity with your local doctor.']]},
'about':{title:'Medicine with clarity and compassion',eyebrow:'About JD Hospital',intro:'An original demonstration healthcare brand built around connected expertise and human-centred care.',sections:[['Our vision','To make advanced healthcare more understandable, coordinated and humane.'],['Our mission','Deliver safe, evidence-led care through trusted teams and thoughtful technology.'],['Our values','Clinical integrity · Compassion · Clarity · Collaboration · Accountability.']]},
'corporate':{title:'JD Hospital corporate',eyebrow:'Governance & organisation',intro:'Company information, leadership, quality commitments and performance reporting.',sections:[['Governance','Responsible oversight, ethical conduct and transparent reporting.'],['Quality commitment','Continuous measurement and learning across the care journey.'],['CSR','Community health, education and responsible environmental practices.']]},
'contact':{title:'We’re here to help',eyebrow:'Contact JD Hospital',intro:'For appointments, hospital information and general enquiries, choose the fastest way to reach us.',sections:[['Appointments','Call +91 712 400 7000 or use online booking.'],['General enquiries','hello@jdhospital.demo'],['Emergency','Call 112 or your nearest JD Hospital emergency department.']]},
'privacy-policy':{title:'Privacy policy',eyebrow:'Your information',intro:'Configurable demonstration privacy content for the JD Hospital platform.',sections:[['Information we collect','Contact and booking information supplied through forms.'],['How it is used','To respond to requests, coordinate care and operate the service.'],['Your choices','Contact the privacy office to request access, correction or deletion where applicable.']]},
'terms':{title:'Website terms',eyebrow:'Terms of use',intro:'These demonstration terms should be reviewed by qualified legal counsel before production use.',sections:[['Acceptable use','Use the platform lawfully and do not interfere with security.'],['Availability','Services and content may change without notice.'],['Clinical services','Online requests are not confirmed appointments until acknowledged.']]},
'disclaimer':{title:'Medical disclaimer',eyebrow:'Important information',intro:'Website information is educational and does not replace care from a qualified healthcare professional.',sections:[['No diagnosis','Content cannot determine your condition or provide individual treatment.'],['Medicines','Never start, stop or change medicines based only on website content.'],['Emergency care','For urgent symptoms, contact emergency services immediately.']]},
'cookie-policy':{title:'Cookie policy',eyebrow:'Website preferences',intro:'This configurable page explains essential, analytics and preference cookies.',sections:[['Essential cookies','Required for secure sessions and core features.'],['Analytics','Optional measurement should only run after appropriate consent.'],['Control','Users should be able to update consent preferences at any time.']]},
'accessibility':{title:'Accessibility',eyebrow:'Care for everyone',intro:'JD Hospital aims to follow WCAG 2.2 AA principles across digital services.',sections:[['Designed for access','Keyboard navigation, visible focus and semantic structure.'],['Alternative formats','Contact us for information in a more accessible format.'],['Feedback','Report accessibility barriers to accessibility@jdhospital.demo.']]}
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug];if(!p)notFound();return <><section className="page-hero"><div className="container"><div className="breadcrumbs">Home / {p.title}</div><span className="eyebrow">{p.eyebrow}</span><h1>{p.title}</h1><p>{p.intro}</p><div className="hero-buttons"><Link className="btn btn-primary" href={slug==='contact'?'/book-appointment':'/book-appointment'}>Book appointment</Link>{['international-patients','contact','insurance'].includes(slug)&&<a className="btn btn-secondary" href="#enquiry">Send enquiry</a>}</div></div></section><section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Explore</span><h2>Clear information. Thoughtful support.</h2></div></div><div className="doctor-grid">{p.sections.map(([t,d])=><article className="quick-card" key={t}><span className="icon-box"><HeartHandshake/></span><h3>{t}</h3><p>{d}</p>{['health-library','news-events','videos'].includes(slug)&&<Link className="quick-link" href="/contact">Request more information</Link>}</article>)}</div>{['health-library','disclaimer'].includes(slug)&&<div className="notice" style={{marginTop:30}}><strong>Medical disclaimer:</strong> Educational information only. Always consult a qualified professional for personal medical advice.</div>}</div></section>{slug==='home-healthcare'&&<section className="section section-tint" id="request"><div className="container" style={{maxWidth:900}}><HomecareForm/></div></section>}{['contact','international-patients','insurance'].includes(slug)&&<section className="section section-tint" id="enquiry"><div className="container" style={{maxWidth:900}}><EnquiryForm type={slug==='international-patients'?'international':slug==='insurance'?'insurance':'general'} title={slug==='international-patients'?'Request international patient assistance':slug==='insurance'?'Ask the insurance desk':'Send us a message'}/></div></section>}</>}
